### PR TITLE
fix: trailing space in method

### PR DESCRIPTION
**Pull request by danifullview**

### CODE REVIEW

**Comment by Dorin-Mocan** [comment]
The trailing space(s) was/were put intentionally for method polymorphism support.

**Comment by danifullview** [comment]
Maybe it could not add any space if there's a single method w/ a given name.
I'm using [nswag](https://github.com/RicoSuter/NSwag) to generate a typescript client, and the methods end up having a trailing underline.

**Comment by Dorin-Mocan** [comment]
@danifullview , yes, I could avoid adding spaces if no polymorphism, but is there really a problem with the generated by nswag typescript client? What's the actual problem that you're facing?

**Comment by Dorin-Mocan** [comment]
I'll make the change and release a new version soon.

**Comment by danifullview** [comment]
I don't want to hardcode the method names on the client, and I want to use the generated method names.

**Comment by Dorin-Mocan** [comment]
I understand, but does the generated code compile and work? Or because of the trailing space the code does not compile/work correctly?

**Comment by danifullview** [comment]
I think swagger has no support for signalR. nswag will generate a rest client based on the swagger json.
I can't actually use that generated client. 
What I want to use, is the name of the method generated by nswag, in my own code.
Maybe `SignalRSwaggerGen` could generate a dynamic enum, containing all the method names in a signalR hub.

**Comment by Dorin-Mocan** [comment]
You want to use the name of the method generated by nswag in your code. Why don't you trim the trailing spaces in your code before invoking the method? I really don't understand :) Anyway, as I said, I'll release a new version with the change you suggested. Give me a couple of hours.

**Comment by danifullview** [comment]
nswag will replace spaces with underliens. I think it's kind of hacky to do processing on the generated names.

Thanks for making the change.

**Comment by Dorin-Mocan** [comment]
I released the version 4.1.0 which solves the trailing spaces problem. Please toss a star for this repo in order to support my work. Thanks for contribution!

**Comment by danifullview** [comment]
Thank you.

**Pull request closed without merging**
